baseURL = "https://brothersaloof.com"
languageCode = "en-us"
title = "The Cliffs at Waterford Spring Lake, NC"
theme = "tricky-triangles"
publishDir = "docs"

[params]
  image = "images/TheCliffs.jpg"
  description = "Welcome to The Cliffs at Waterford, more to come...."
[params.property]
  name = "The Cliffs at Waterford"
  phone = "910.339.0550"
  email = "tbd@gmail.com"
[params.property.address]
  line1 = "859 Cliff Cir"
  line2 = "Spring Lake, NC 28390"
  mapURL = "https://www.google.com/maps/embed/v1/place?key=AIzaSyDU3vr9H2kUSnkmkvgWmxSNNl60NbV8U9Q&q=The%20Cliffs%20at%20Waterford%20Spring%20Lake%20NC&zoom=14"
