baseURL = "https://brothersaloof.com"
languageCode = "en-us"
title = "The Cliffs at Waterford Spring Lake, NC"
theme = "tricky-triangles"
publishDir = "docs"

[params]
  image = "images/TheCliffs.jpg"
  description = "Welcome to The Cliffs at Waterford, more to come...."
[params.property]
  name = "The Cliffs at Waterford"
  phone = "910.339.0550"
  email = "thecliffsatwaterfordmgr@gmail.com"
[params.property.address]
  line1 = "859 Cliff Cir"
  line2 = "Spring Lake, NC 28390"
